### ISSUE TITLE
database_statistics report is down

### ISSUE THREAD

**Issue by phiphou** [openstreetmap/operations#435]
Hi,

It's been more than two weeks that [https://taginfo.openstreetmap.org/reports/database_statistics](https://taginfo.openstreetmap.org/reports/database_statistics) returns Internal Server Error. Can you fix this ?

Thanks

**Comment by tomhughes** [comment]
That's up to @joto really - you can report it at https://github.com/taginfo/taginfo/issues though I believe he's already aware there are some issues since the Ubuntu 20.04 upgrade on the server.

**Comment by joto** [comment]
I have looked into this and can't make head or tail of it. I set up a test system with Ubuntu 20.04 and similar setup and it doesn't show this problem. And then there are all these `Passenger AppPreloader: /srv/taginfo.openstreetmap.org/taginfo/web (forking...)` processes on the server. Maybe something went wrong with the update and now it loads a wrong library version or something.

@tomhughes How much effort would it be to reinstall the server from scratch, copying over the database files (especially the `taginfo-history.db` needs to be preserved)?

btw: https://taginfo.openstreetmap.org/reports/historic_development also doesn't work

**Comment by tomhughes** [comment]
The `AppPreloader` processes are normal - those are just the passenger processes that are serving requests.

When I hit that URL I see an exception in the error log:

```
App 3841049 output: 2020-07-15 07:31:51 - FloatDomainError - NaN:
App 3841049 output: 	/srv/taginfo.openstreetmap.org/taginfo/web/views/reports/database_statistics.erb:45:in `to_i'
App 3841049 output: 	/srv/taginfo.openstreetmap.org/taginfo/web/views/reports/database_statistics.erb:45:in `block in singleton class'
App 3841049 output: 	/srv/taginfo.openstreetmap.org/taginfo/web/views/reports/database_statistics.erb:-2:in `instance_eval'
App 3841049 output: 	/srv/taginfo.openstreetmap.org/taginfo/web/views/reports/database_statistics.erb:-2:in `singleton class'
App 3841049 output: 	/srv/taginfo.openstreetmap.org/taginfo/web/views/reports/database_statistics.erb:-5:in `__tilt_2220'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:839:in `render'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:682:in `erb'
App 3841049 output: 	/srv/taginfo.openstreetmap.org/taginfo/web/taginfo.rb:107:in `erb'
App 3841049 output: 	/srv/taginfo.openstreetmap.org/taginfo/web/lib/ui/reports.rb:17:in `block (2 levels) in <class:Taginfo>'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/rack-contrib-2.0.1/lib/rack/contrib/jsonp.rb:37:in `call'
App 3841049 output: 	/usr/lib/ruby/vendor_ruby/rack/logger.rb:15:in `call'
App 3841049 output: 	/usr/lib/ruby/vendor_ruby/rack/common_logger.rb:33:in `call'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
App 3841049 output: 	/usr/lib/ruby/vendor_ruby/rack/head.rb:12:in `call'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
App 3841049 output: 	/var/lib/gems/2.7.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
App 3841049 output: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
App 3841049 output: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 3841049 output: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 3841049 output: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 3841049 output: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by tomhughes** [comment]
Well all the calculated values in that screen removed it displayed and all the statistics are coming up as zero which is why the maths on the divisions is mailing.

**Comment by tomhughes** [comment]
When I run a select on the database with the sqlite command line I get sensible values and I can see that ruby is managing to open and read the database correctly so all a bit odd...

**Comment by joto** [comment]
Yes, exactly the same what I have been trying. The data is there but it still comes up "not there".

**Comment by tomhughes** [comment]
I added some logging to the `stats` method and I see lots of successful calls but when I hit that specific page all the calls just come back with no result from the select so it's somehow specific to that page.

**Comment by tomhughes** [comment]
So it's some sort of encoding issue or something. I installed a trace handler on the master database that logs all the SQL executed and the working queries log like:

```
Trace: SELECT value FROM master_stats WHERE key='nodes_with_tags'
```

while the failing ones log like:

```
Trace: SELECT value FROM master_stats WHERE key=x'6f626a6563745f74616773'
```

so for some reason it has turned the ASCII value of the key into a hex string!

**Comment by tomhughes** [comment]
Yes - the failing ones the argument to `stats` has `key.encoding` of `ASCII-8BIT` while the working ones are `UTF-8`.

**Comment by tomhughes** [comment]
Forcing encoding definitely fixes both reports - this was my "solution" that worked:

```patch
diff --git a/web/lib/sql.rb b/web/lib/sql.rb
index 789b990..27b6610 100644
--- a/web/lib/sql.rb
+++ b/web/lib/sql.rb
@@ -100,7 +100,7 @@ module SQL
         end
 
         def stats(key)
-            get_first_value('SELECT value FROM master_stats WHERE key=?', key).to_i
+            get_first_value('SELECT value FROM master_stats WHERE key=?', key.encode(Encoding::UTF_8)).to_i
         end
 
         def quote(data)
diff --git a/web/viewsjs/reports/historic_development.js.erb b/web/viewsjs/reports/historic_development.js.erb
index 05ca6ae..4978525 100644
--- a/web/viewsjs/reports/historic_development.js.erb
+++ b/web/viewsjs/reports/historic_development.js.erb
@@ -3,6 +3,7 @@ page = @trans.t.reports.historic_development
 
 data = {}
 ['num_keys', 'num_tags', 'relation_types'].each do |key|
+    key.encode!(Encoding::UTF_8)
     data[key] = @db.execute("SELECT udate, value FROM history.history_stats WHERE key=? ORDER BY udate", key).map do |row|
         [ row['udate'], row['value'].to_i ]
     end
```

**Comment by joto** [comment]
Thanks @tomhughes for looking into this and finding the encoding problem. It still doesn't make any sense to me. UTF-8 should be the default and it seems to be everywhere but in this one case. And it works on other machines. I tried forcing encoding in several places and it doesn't change anything.

**Comment by tomhughes** [comment]
It's weird.. We already force `external_encoding` and I tried forcing `internal_encoding` as well and that fixes one of them but not the other.

It's currently live as a hack but we should add the change to the repo properly or something,

**Comment by joto** [comment]
Took me forever, but I found the culprit: There was a stray `erubi` gem installed on the server. After removing that everything now works.

**Comment by tomhughes** [comment]
Ah I think I installed that after the OS upgrade because there were some errors in the log that seemed to suggest it was missing.
