### ISSUE TITLE
Scripts no longer load on the wiki

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#471]
Scripts no longer load on the wiki due to an error at page load:

```
[a66d5682d96c9e5d25505a16] 2020-11-02 22:34:01: Fatal exception of type "InvalidArgumentException"

[a66d5682d96c9e5d25505a16] 2020-11-02 22:34:03: Fatal exception of type "InvalidArgumentException"

[a66d5682d96c9e5d25505a16] 2020-11-02 22:34:03: Fatal exception of type "InvalidArgumentException"

[a66d5682d96c9e5d25505a16] 2020-11-02 22:34:03: Fatal exception of type "InvalidArgumentException"

Problematic modules: {
    "startup": "error"
}
```

This affects many MediaWiki features, including the notification panel, visual editor, recent changes filters, and even the preferences page. It started happening sometime within the past 24 hours.

**Comment by ArloJamesBarnes** [comment]
login too

**Comment by tomhughes** [comment]
Mediawiki has been upgraded - happy to help with a fix if anybody knows what is wrong.

**Comment by tomhughes** [comment]
Seems to be something to do with wikibase - disabling the wikibase extension seems to stop the errors.

Maybe @nyurik has some ideas?

**Comment by tomhughes** [comment]
I believe these are the actual errors:

```
2020-11-03 10:38:03 tabaluga.openstreetmap.org wiki: Calculating version for "startup" failed: [Exception InvalidArgumentException( /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderFileModule.php:267) A module may not set both 'scripts' and 'packageFiles']
#0 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(534): ResourceLoaderFileModule->__construct()
#1 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderStartUpModule.php(184): ResourceLoader->getModule()
#2 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderStartUpModule.php(405): ResourceLoaderStartUpModule->getModuleRegistrations()
#3 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderModule.php(736): ResourceLoaderStartUpModule->getScript()
#4 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent()
#5 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderModule.php(839): ResourceLoaderModule->getModuleContent()
#6 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(775): ResourceLoaderModule->getVersionHash()
#7 [internal function]: ResourceLoader->{closure}()
#8 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(787): array_map()
#9 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(874): ResourceLoader->getCombinedVersion()
#10 /srv/wiki.openstreetmap.org/w/load.php(51): ResourceLoader->respond()
#11 /srv/wiki.openstreetmap.org/w/load.php(38): wfLoadMain()
#12 {main}
2020-11-03 10:38:03 tabaluga.openstreetmap.org wiki: Preloading module info from startup failed: [Exception InvalidArgumentException( /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderFileModule.php:267) A module may not set both 'scripts' and 'packageFiles']
#0 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(534): ResourceLoaderFileModule->__construct()
#1 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(133): ResourceLoader->getModule()
#2 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderStartUpModule.php(172): ResourceLoader->preloadModuleInfo()
#3 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderStartUpModule.php(405): ResourceLoaderStartUpModule->getModuleRegistrations()
#4 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderModule.php(736): ResourceLoaderStartUpModule->getScript()
#5 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent()
#6 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(1191): ResourceLoaderModule->getModuleContent()
#7 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(899): ResourceLoader->makeModuleResponse()
#8 /srv/wiki.openstreetmap.org/w/load.php(51): ResourceLoader->respond()
#9 /srv/wiki.openstreetmap.org/w/load.php(38): wfLoadMain()
#10 {main}
2020-11-03 10:38:03 tabaluga.openstreetmap.org wiki: Generating module package failed: [Exception InvalidArgumentException( /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderFileModule.php:267) A module may not set both 'scripts' and 'packageFiles']
#0 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(534): ResourceLoaderFileModule->__construct()
#1 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderStartUpModule.php(184): ResourceLoader->getModule()
#2 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderStartUpModule.php(405): ResourceLoaderStartUpModule->getModuleRegistrations()
#3 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderModule.php(736): ResourceLoaderStartUpModule->getScript()
#4 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent()
#5 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(1191): ResourceLoaderModule->getModuleContent()
#6 /srv/wiki.openstreetmap.org/w/includes/resourceloader/ResourceLoader.php(899): ResourceLoader->makeModuleResponse()
#7 /srv/wiki.openstreetmap.org/w/load.php(51): ResourceLoader->respond()
#8 /srv/wiki.openstreetmap.org/w/load.php(38): wfLoadMain()
#9 {main}
```

**Comment by tomhughes** [comment]
Looks like https://github.com/openstreetmap/chef/commit/12373912a3f62b857cb7de5355079cc6bceb5fbd has fixed it and wikibase is now enabled again.
