### ISSUE TITLE
Error generating tile logs for 2021-07-23

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#581]
When backfilling the tile logs one single day, 2021-07-23, failed with:

```
Generating files for 2021-07-23
Traceback (most recent call last):
  File "/opt/tilelog/bin/tilelog", line 8, in <module>
    sys.exit(cli())
  File "/opt/tilelog/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/tilelog/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/tilelog/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/tilelog/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/tilelog/lib/python3.8/site-packages/tilelog/__init__.py", line 20, in cli
    tile_logs(curs, date)
  File "/opt/tilelog/lib/python3.8/site-packages/tilelog/__init__.py", line 38, in tile_logs
    curs.execute(query, {"year": date.year, "month": date.month,
  File "/opt/tilelog/lib/python3.8/site-packages/pyathena/util.py", line 37, in _wrapper
    return wrapped(*args, **kwargs)
  File "/opt/tilelog/lib/python3.8/site-packages/pyathena/cursor.py", line 108, in execute
    raise OperationalError(query_execution.state_change_reason)
pyathena.error.OperationalError: HIVE_BAD_DATA: Error parsing field value 'TLSv1.2' for field 2: For input string: "TLSv1.2"
```

**Comment by pnorman** [comment]
Fixed in version 221 of fastly config at the time. I don't think it's worth the time to figure out how to recreate that day's logs.
