### ISSUE TITLE
API endpoints sporadically rejecting connections

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#597]
### URL

https://api.openstreetmap.org/api/0.6/changeset/create

### How to reproduce the issue?

Sporadically the backed API endpoints seem to be rejecting client connections.

### Screenshot(s) or anything else?

Example rejected connection on JOSM upload:

```
2022-02-28 18:47:13.388 INFO: PUT https://api.openstreetmap.org/api/0.6/changeset/create (229 B) ...
2022-02-28 18:47:13.391 INFO: PUT https://api.openstreetmap.org/api/0.6/changeset/create -> !!! (1 ms)
2022-02-28 18:47:13.391 WARNING: java.net.SocketException: Unexpected end of file from server. Cause: java.net.SocketException: Unexpected end of file from server
java.net.SocketException: Unexpected end of file from server
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at org.openstreetmap.josm.tools.Http1Client$1.getResponseCode(Http1Client.java:94)
	at org.openstreetmap.josm.tools.HttpClient.connect(HttpClient.java:152)
	at org.openstreetmap.josm.tools.HttpClient.connect(HttpClient.java:124)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:729)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:673)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:668)
	at org.openstreetmap.josm.io.OsmApi.sendPutRequest(OsmApi.java:663)
	at org.openstreetmap.josm.io.OsmApi.openChangeset(OsmApi.java:463)
	at org.openstreetmap.josm.io.OsmServerWriter.uploadOsm(OsmServerWriter.java:202)
	at org.openstreetmap.josm.gui.io.UploadPrimitivesTask.realRun(UploadPrimitivesTask.java:266)
	at org.openstreetmap.josm.gui.io.AsynchronousUploadPrimitivesTask.realRun(AsynchronousUploadPrimitivesTask.java:129)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:94)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3135)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:295)
	at org.openstreetmap.josm.tools.Http1Client$1.getResponseVersion(Http1Client.java:85)
	... 15 more

2022-02-28 18:47:13.392 INFO: Message notifier active (checks every 60 minutes)
2022-02-28 18:47:13.547 SEVERE: org.openstreetmap.josm.io.OsmTransferException: java.net.SocketException: Unexpected end of file from server. Cause: java.net.SocketException: Unexpected end of file from server. Cause: java.net.SocketException: Unexpected end of file from server
org.openstreetmap.josm.io.OsmTransferException: java.net.SocketException: Unexpected end of file from server
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:777)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:673)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:668)
	at org.openstreetmap.josm.io.OsmApi.sendPutRequest(OsmApi.java:663)
	at org.openstreetmap.josm.io.OsmApi.openChangeset(OsmApi.java:463)
	at org.openstreetmap.josm.io.OsmServerWriter.uploadOsm(OsmServerWriter.java:202)
	at org.openstreetmap.josm.gui.io.UploadPrimitivesTask.realRun(UploadPrimitivesTask.java:266)
	at org.openstreetmap.josm.gui.io.AsynchronousUploadPrimitivesTask.realRun(AsynchronousUploadPrimitivesTask.java:129)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:94)
	at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at org.openstreetmap.josm.tools.Http1Client$1.getResponseCode(Http1Client.java:94)
	at org.openstreetmap.josm.tools.HttpClient.connect(HttpClient.java:152)
	at org.openstreetmap.josm.tools.HttpClient.connect(HttpClient.java:124)
	at org.openstreetmap.josm.io.OsmApi.sendRequest(OsmApi.java:729)
	... 12 more
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3135)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:295)
	at org.openstreetmap.josm.tools.Http1Client$1.getResponseVersion(Http1Client.java:85)
	... 15 more

2022-02-28 18:47:13.554 SEVERE: Network exception - <html>Failed to open a connection to the remote server<br>'https://api.openstreetmap.org/api/0.6/'.<br>Please check your internet connection.</html> 
```

**Comment by tomhughes** [comment]
Moved to operations as this is clearly not a rails code issue.

I looked into this when it was first reported and there is absolutely no sign of these requests on the server which is really that surprising given that it appears to be a network connection issue.

Given we are not getting widespread reports of problems my assumption is that this is an issue between a particular network and our data centre and probably outside out control.

**Comment by Firefishy** [comment]
I have not been able to replicate it. May have just a JOSM issue.

**Comment by mmd-osm** [comment]
Further discussion on the topic is now happening in https://josm.openstreetmap.de/ticket/22160 

Error message in the JOSM ticket is the same as the one mentioned here "java.net.SocketException: Unexpected end of file from server",  and it also affects the following endpoints, which are being served by the [Rails port](https://github.com/openstreetmap/chef/blob/master/cookbooks/web/templates/default/apache.backend.erb#L72), I believe.

```
PUT https://api.openstreetmap.org/api/0.6/changeset/create
PUT https://api.openstreetmap.org/api/0.6/changeset/55555
```

**Comment by mmd-osm** [comment]
@tomhughes : I'm not sure if you have some bandwidth to keep an eye on the discussion over at the JOSM issue. @flohoff mentioned in one of his last remarks, that "_My guess is that in late 2021 or early 2022 either JOSM changed to HTTP/1.1 or HTTP keepalive or the Admins for the OSM API reduced the keepalive timeout on their end or even introduced keepalive._".

We're still a bit unclear if this issue is caused by osm.org, by JOSM, or even both. I think it would be helpful it we could somehow rule out any changes on osm.org (be it on Apache, or Rails port).

**Comment by tomhughes** [comment]
I've been ignoring it until somebody provides actionable information that actually points at a problem.

At the very least in order to look at the logs I need a concrete example with timestamps that I can look for - just giving me a URL and expecting me to abuse the API until it fails is useless if only because I don't want to create loads of changesets I'm not going to use!

To answer your question about keepalive I am not aware of any changes on our end but if a client is going to use it then it has to expect that the server might have timed it out and that the connection might be closed by the time it tries to send a new request.

**Comment by mmd-osm** [comment]
Investigation is still ongoing. It seems to be some kind of keep-alive timeout race condition, which presumably isn't handled correctly by JOSM.

It only happens on Rails endpoints in case there's a delay of about 5 seconds between sending a first request and then trying to reuse the same connection to issue a second request. By the way, 5 seconds happens to be the keep-alive timeout reported in the Apache response.

Switching between HTTP/1.1 and HTTP/2 didn't make much of a difference.

**Comment by zorun** [comment]
In a totally different context than OSM, we had a similar issue of randomly dropped requests, and the only relevant error in Apache logs was `error reading status line from remote server`. When a request was dropped like this, the backend service behind Apache wouldn't see the request at all.

It turns out to be a race condition in Apache reverse proxy pooling, which can be "solved" with this config:

```
SetEnv proxy-initial-not-pooled 1
```
The Apache doc explains the problem: https://httpd.apache.org/docs/current/mod/mod_proxy_http.html#env
Despite the warning we haven't seen any performance impact with this option.

**Comment by tomhughes** [comment]
Thanks, but I don't see any sign of that error in our logs and we haven't been doing any HTTP reverse proxying for some time - we do proxy some requests (those which use cgimap) using `proxy_fcgi` but we don't use `proxy_http` these days.

**Comment by Firefishy** [comment]
My suggestion is we disable HTTP/1 based keepalive (client side) in Apache for a week or 2 and evaluate.

**Comment by mmd-osm** [comment]
My suggestion would be to discuss any changes on the server side in https://josm.openstreetmap.de/ticket/22160 , otherwise it will be extremely difficult for josm maintainers to figure out what’s really going on.
