### ISSUE TITLE
Add Translate extension to main wiki

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#649]
There has been some discussion among the wiki editors whether to add the translate extension. @lectrician1 wrote a [proposal](https://wiki.openstreetmap.org/w/index.php?title=Proposed_features/Add_Translate_extension_to_Wiki&oldid=2344717) that was subsequently accepted. Before the extension can be installed as intended, MediaWiki needs to be updated to version 1.38 (currently 1.37). I can write a PR that adds the extension. 

Includes/obsoletes #555

**Comment by tomhughes** [comment]
Given how traumatic the last upgrade was I'm in no hurry to do another without some sort of guarantees that it isn't going to break everything.

**Comment by lectrician1** [comment]
Could someone look into doing this now?

**Comment by Tigerfell** [comment]
This is currently blocked by #749.

**Comment by tomhughes** [comment]
I've installed this on https://test.wiki.openstreetmap.org/ for evaluation - install appears to have worked without issues.

I suspect there may be some configuration needed to make it usable though?

**Comment by 1ec5** [comment]
Thank you! Configuring this extension will probably be an ongoing task as we figure out how much the community will really tolerate this extension. It’s more straightforward for conventional pages, but we’ll probably need to tread more carefully on tagging pages for backwards compatibility with scrapers like taginfo.

The first thing we need to do is [update the user groups](https://wiki.openstreetmap.org/w/index.php?title=Proposed_features/Add_Translate_extension_to_Wiki&oldid=2344717#User_rights). In particular, logged-in users need the `translate` right, and a new user group for [translation administrators](https://www.mediawiki.org/wiki/Special:ListGroupRights#translationadmin) needs the `translate-import`, `translate-manage`, `pagelang`, and `pagetranslation` permissions. We can add all the administrators to this group to start out with, and I’ll lean on the bureaucrats to add more. I’ve marked [this page](https://test.wiki.openstreetmap.org/wiki/Vienna_Convention_on_Road_Signs_and_Signals) for content translation, but no one can actually translate it until the rights are in place.

Separately, we should [add some message groups](https://www.mediawiki.org/wiki/Help:Extension:Translate/Unstructured_element_translation). For the test wiki, we only need one to kick the tires on. I can configure the messages that are part of it on the wiki, once the group itself exists in LocalSettings.php.

In production, we’ll probably make use of more groups. Based on [our most translated interface messages](https://wiki.openstreetmap.org/wiki/Special:PrefixIndex/MediaWiki:) and the requests I often get, the following groups would be useful for keeping things organized:

* `gadgets-messages` for [gadget](https://wiki.openstreetmap.org/wiki/Special:Gadgets) metadata
* `noarticle-messages` for our 404 pages
* `sidebar-messages` for anything that appears in the sidebar
* `taginfo-messages` for the AJAX-based [taginfo gadget](https://wiki.openstreetmap.org/wiki/Template:Taginfo2#Translations)
* `tags-messages` for [tag](https://wiki.openstreetmap.org/wiki/Special:Tags) metadata
* `wikibase-messages` for our Wikibase instance

Maybe @maro-21 has more ideas. By default, even translations of MediaWiki: messages are locked down to administrators only. If this turns out to be a burden, we could separately track creating a user group for interface administrators who only have the right to edit this namespace, without all the other administrator stuff.

We only need to create message groups for interface messages or other things in the MediaWiki: namespace that templates use. Page content in general can use content translation, which administrators should be able to handle on-wiki without your intervention.

**Comment by tomhughes** [comment]
If somebody can provide a suitable PHP fragment for me to review then that would be helpful - there's guidance at https://www.mediawiki.org/wiki/Help:Extension:Translate/Configuration.

At the very least I need to know what group to use for "logged in users" in order to give them permissions... I assume there is actually a group for that but I'm not actually sure there is?

As to administrators can a group be created from the settings file or does that need to be done from the web interface before I can assign permissions to it?

**Comment by 1ec5** [comment]
openstreetmap/chef#568 has the specific PHP configuration you can use. I think the user groups part is still current, other than ideally granting `translate-import` and `pagelang` permissions alongside the other ones. “Logged-in users” is what the proposal called it, but `autoconfirmed` is a more reasonable group to assign to. The group needs to be created and configured in PHP, and then a bureaucrat can use the Web interface to assign users to the group (or we can make it so that administrators can add users to the group too).

**Comment by tomhughes** [comment]
I've added https://github.com/openstreetmap/chef/commit/bbb97ede0cf9a1453381ed4fb7972e3b7742078f based on that PR though I'm not sure about the bit that disabled captchas, or are they only shown to unconfirmed users that that isn't needed if we're limiting translation to confirmed users?

**Comment by 1ec5** [comment]
Right, our `autoconfirmed` group already has the `skipcaptcha` right, so it should be redundant. (It appears to be a reference to https://phabricator.wikimedia.org/T36182, which is still outstanding after all these years.)

Can you [add me](https://test.wiki.openstreetmap.org/wiki/Special:UserRights/Minh_Nguyen) to the translationadmin user group?

**Comment by tomhughes** [comment]
You should now be in the admin group.

**Comment by 1ec5** [comment]
Thanks, it’s working pretty well as far as I can tell. For example, here’s [a translation](https://test.wiki.openstreetmap.org/wiki/Vienna_Convention_on_Road_Signs_and_Signals/vi) of the Vienna Convention article, which I’ve dirtied a few times. I’ve also added it to [an aggregate group](https://test.wiki.openstreetmap.org/wiki/Special:AggregateGroups) for discoverability.

A few observations:

* Special:SearchTranslations returns an error for seemingly every query. For example, [`xem`](https://test.wiki.openstreetmap.org/w/index.php?title=Special%3ASearchTranslations&query=xem) returns:
    > [50369e01019abefef6002c2d] 2025-05-04 23:42:49: Fatal exception of type "TypeError"
   
   Maybe something to do with the search failures in https://github.com/openstreetmap/operations/issues/903#issuecomment-2849289301?
* I haven’t gotten translation memory to appear yet. Maybe this is just because I haven’t marked enough pages for translation, or the `$wgTranslateTranslationServices` setting needs to be double-checked, or it has something to do with that `TypeError`.
* We have a large number of translatable templates and several competing approaches to making them translatable. One of the approaches is to rely on MediaWiki: interface messages, which can only be translated by administrators, which is a bummer. The Translate extension comes with a built-in solution, [message bundles](https://www.mediawiki.org/wiki/Help:Extension:Translate/Message_Bundles#Enabling_message_bundle_integration), but I don’t know if it’s mature yet. I can request configuring that separately once we get content translation set up.

And a few notes for wiki contributors:

* At the outset, I expect translation administrators to enable content translation very intentionally for certain kinds of pages: articles about policies and guidelines, articles about real-world phenomena (including feature description pages), articles about software packages, user manuals, WikiProject pages affecting multilingual regions, and possibly some tagging proposal pages. These genres don’t have much software integration that would raise backwards compatibility concerns. We should not enable it for any key, tag, and relation description pages until we’re confident that scrapers (especially taginfo) can handle any markup changes.
* Translation administrators should proceed on a case-by-case basis, mindful of any potentially controversial topics. There are still many unresolved discrepancies between local communities in terms of their tagging conventions. We should avoid steamrolling these differences. A good strategy is to create very coarse translation units with minimal variables, providing structure and a starting point for brand-new translations without making translators feel like the English version is a straightjacket.
* The content translation system uses a different page title format than we’ve been using: /xyz as a subpage instead of Xyz: as a pseudonamespace. I’m pretty sure the format isn’t configurable, but by default, translations can completely override the display title, obscuring the raw page title. The subpage approach integrates better with the rest of MediaWiki’s functionality, such as Special:MyLanguage, which replaces the clunky and expensive `{{LL}}` template.
* The Translate extension has its own `<languages />` tag for inserting a language bar. It should only be used on pages marked for content translation, and those pages should no longer use our homegrown `{{languages}}` template. I haven’t found a way to integrate the tag into the template conditionally, probably because the tag gets expanded too late.
* If you start a new translation of a page that’s linked to a data item, you still need to manually add it to the data item’s [documentation wiki pages <small>(P31)</small>](https://wiki.openstreetmap.org/wiki/Property:P31) statement. This should be very rare for the time being. If and when we expand content translation to tagging-related pages, Special:MyLanguage may greatly reduce the need to manually maintain a list of translations. At this point, taginfo would be the main point of concern, since the maintainer has declined to support data items.
* We should make an aggregate group for each local community, so that their WikiProject pages can all have the local language as the base language for translation. This will save administrators the trouble of manually setting the page content language or moving pages to the correct namespace.
* Note the special instructions for [making images, headings, and categories translatable](https://www.mediawiki.org/wiki/Help:Extension:Translate/Page_translation_example#Step_5:_Adding_other_wiki_elements). There’s a subtle whitespace difference for headings.

**Comment by tomhughes** [comment]
Not all the current language prefixes are pseudo namespaces - some are real namespaces.

**Comment by 1ec5** [comment]
Yeah, that too. 😣 It’s very much an [xkcd 927](https://xkcd.com/927/) situation. At least the pages marked for content translation will involve fewer templates than the old way. I’d be interested in eventually migrating everything out of the language namespaces and pseudonamespaces for consistency and discoverability. One thing at a time.

**Comment by tomhughes** [comment]
There's going to be a lot of knock on effects on other projects like taginfo that build their own databases of links to wiki documentation.

**Comment by 1ec5** [comment]
We might be able to mitigate that to some extent using redirects or by encouraging those clients to migrate to data items, but let’s skirt any of that for now by focusing on non-tagging-related pages. I don’t know of anyone actively scraping, say, translations of WikiProject pages looking for machine-readable content. The closest thing is [osm-legal-default-speeds](https://github.com/westnordost/osm-legal-default-speeds/), but “[Default speed limits](https://wiki.openstreetmap.org/wiki/Default_speed_limits)” probably isn’t a good candidate for content translation anyways.

**Comment by tomhughes** [comment]
> * Special:SearchTranslations returns an error for seemingly every query. For example, [`xem`](https://test.wiki.openstreetmap.org/w/index.php?title=Special%3ASearchTranslations&query=xem) returns:

This is the full trace:

```
[2a54ee77b9e2cd16bdb7f70e] /w/index.php?title=Special%3ASearchTranslations&query=xem TypeError: Elastica\Client::_prepareConnectionParams(): Argument #1 ($config) must be of type array, string given, called in /srv/test.wiki.openstreetmap.org/w/vendor/ruflin/elastica/src/Client.php on line 674

Backtrace:

from /srv/test.wiki.openstreetmap.org/w/vendor/ruflin/elastica/src/Client.php(699)
#0 /srv/test.wiki.openstreetmap.org/w/vendor/ruflin/elastica/src/Client.php(674): Elastica\Client->_prepareConnectionParams()
#1 /srv/test.wiki.openstreetmap.org/w/vendor/ruflin/elastica/src/Client.php(85): Elastica\Client->_initConnections()
#2 /srv/test.wiki.openstreetmap.org/w/extensions/Translate/src/TtmServer/ElasticSearchTtmServer.php(445): Elastica\Client->__construct()
#3 /srv/test.wiki.openstreetmap.org/w/extensions/Translate/src/TtmServer/ElasticSearchTtmServer.php(463): MediaWiki\Extension\Translate\TtmServer\ElasticSearchTtmServer->getClient()
#4 /srv/test.wiki.openstreetmap.org/w/extensions/Translate/src/TtmServer/ElasticSearchTtmServer.php(629): MediaWiki\Extension\Translate\TtmServer\ElasticSearchTtmServer->getIndex()
#5 /srv/test.wiki.openstreetmap.org/w/extensions/Translate/src/TtmServer/ElasticSearchTtmServer.php(637): MediaWiki\Extension\Translate\TtmServer\ElasticSearchTtmServer->createSearch()
#6 /srv/test.wiki.openstreetmap.org/w/extensions/Translate/src/TtmServer/SearchTranslationsSpecialPage.php(124): MediaWiki\Extension\Translate\TtmServer\ElasticSearchTtmServer->search()
#7 /srv/test.wiki.openstreetmap.org/w/includes/specialpage/SpecialPage.php(728): MediaWiki\Extension\Translate\TtmServer\SearchTranslationsSpecialPage->execute()
#8 /srv/test.wiki.openstreetmap.org/w/includes/specialpage/SpecialPageFactory.php(1724): MediaWiki\SpecialPage\SpecialPage->run()
#9 /srv/test.wiki.openstreetmap.org/w/includes/actions/ActionEntryPoint.php(504): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#10 /srv/test.wiki.openstreetmap.org/w/includes/actions/ActionEntryPoint.php(146): MediaWiki\Actions\ActionEntryPoint->performRequest()
#11 /srv/test.wiki.openstreetmap.org/w/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#12 /srv/test.wiki.openstreetmap.org/w/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#13 {main}
```

**Comment by tomhughes** [comment]
I've applied https://github.com/openstreetmap/chef/commit/8fa246308d377b937de7fb5375f4d6287830ab84 to fix the initial Special:SearchTranslations error and it now hits the other elacticsearch error.

**Comment by maro-21** [comment]
> Maybe [@maro-21](https://github.com/maro-21) has more ideas

I don't have more ideas. I think we should limit translations to gadgets, sidebar and mediawiki messages. Although the extension would be a good tool for translating articles that are dominated by plain text, such as Automated_Edits_code_of_conduct or Import/Guidelines. So that they are always up to date for readers in different languages.
I am against the revolution because of the confusion it will cause and the declining number of OSM Wiki editors.

**Comment by 1ec5** [comment]
It sounds like we’re mostly on the same page. Since you’re on track to be an administrator, it’ll be important to have your support maintaining whatever we end up with. For the tagging-related pages, even just replacing the namespaces with subpages would be a major change, let alone marking them for content translation, so we definitely shouldn’t rush to do that. But there are a number of pages – those prose-heavy ones – that will benefit from content translation anyhow.

**Comment by 1ec5** [comment]
> Special:SearchTranslations returns an error for seemingly every query.

As of the upgrade to MediaWiki 1.46, I’m getting the following message with no additional details:

> The search service is temporarily unavailable.

Translation memory isn’t working so far between the articles I’ve made translatable.
