### ISSUE TITLE
Install WikibaseCirrusSearch on the wiki

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#903]
### Sysadmin

- [X] I am a wiki sysadmin

### Extension name

WikibaseCirrusSearch

### Extension website on medaiwiki.org

https://www.mediawiki.org/wiki/Extension:WikibaseCirrusSearch

### Minimum mediawiki version

1.33+

### Supported

- [X] The wiki extension is listed as release status: stable
- [X] The extension is used on one or more Wikimedia projects
- [X] The extension has versioned releases for the version of Mediawiki used by the OSMF, and for the latest version of Mediawiki

### Purpose

```markdown
The CirrusSearch and Wikibase extensions are both installed but don’t know anything about each other. WikibaseCirrusSearch is the glue between them, allowing users to search for data items by statements and descriptions using a few additional search operators. It would restore some of the functionality that we lost when Sophox went belly-up (Sophox/sophox#31), but with a syntax that’s easier to learn than SPARQL.

See [this proposal](https://wiki.openstreetmap.org/w/index.php?title=Talk:Wiki&oldid=prev&diff=2549798#Install_the_WikibaseCirrusSearch_extension) for the full rationale and examples. So far, there has been relatively little response, just a modicum of support and no explicit opposition.
```

### Special install instructions

```markdown
Releases are available for MediaWiki [1.39](https://packagist.org/packages/wikibase/cirrussearch#dev-REL1_39) and [1.40](https://packagist.org/packages/wikibase/cirrussearch#dev-REL1_40).
```

**Comment by maro-21** [comment]
I support installing this extension - it will help to find missing translations and will help and speed up translations.

Discussion on Wiki: https://wiki.openstreetmap.org/w/index.php?title=Talk:Wiki&oldid=2581889#Install_the_WikibaseCirrusSearch_extension

**Comment by 1ec5** [comment]
This extension would enable iD to provide documentation about relation roles based on existing data items without requiring the creation of redundant redirect pages: https://github.com/ideditor/schema-builder/pull/174#discussion_r1893689779.

**Comment by maro-21** [comment]
What stops us from adding this extension? Do you have any doubts, there isn't any volunteer to do it, or you need more time to think?

**Comment by tomhughes** [comment]
I've installed this on https://test.wiki.openstreetmap.org/ for evaluation - install appears to have worked without issues.

**Comment by 1ec5** [comment]
A search for [`haswbstatement:P6=Q15`](https://test.wiki.openstreetmap.org/w/index.php?search=haswbstatement%3AP6%3DQ15&title=Special%3ASearch&profile=advanced&fulltext=1&ns120=1) turns up nothing, even though plenty of items have a [status <small>(P6)</small>](https://wiki.openstreetmap.org/wiki/Property:P6) of [approved <small>(Q15)</small>](https://wiki.openstreetmap.org/wiki/Item:Q15), such as [bridge:movable <small>(Q104)</small>](https://wiki.openstreetmap.org/wiki/Item:Q104). (An analogous search for [`haswbstatement:P31=Q125407069`](https://www.wikidata.org/w/index.php?search=haswbstatement%3AP31%3DQ125407069&title=Special%3ASearch&profile=advanced&fulltext=1&ns0=1) on Wikidata does work, so the search syntax is correct.) I wonder if there’s any additional step involved in reindexing items based on the new extension, or maybe something to configure because our items are in the Item: namespace instead of the main namespace.

**Comment by tomhughes** [comment]
Did you include `useCirrus=1` in the search parameters?

We can make that the default by setting `$wgWBCSUseCirrus` in the configuration but according to https://www.mediawiki.org/wiki/Extension:WikibaseCirrusSearch#Configuration by default you have to explicitly ask for it.

**Comment by 1ec5** [comment]
I just tried adding it and it didn’t seem to have any effect. 😕

**Comment by tomhughes** [comment]
Is our wiki base data actually being indexed by our elasticsearch already I wonder, or do we need to do something to index it?

**Comment by tomhughes** [comment]
Oh actually I think I misunderstood the configuration thing - the `useCirrus` parameter only works if `$wgWBCSUseCirrus` is null but by default it is `false`.

**Comment by tomhughes** [comment]
Well I've added that to the config now but it doesn't seem to have helped.

**Comment by 1ec5** [comment]
Oh, I should’ve checked first: a normal query for [`highway`](https://test.wiki.openstreetmap.org/w/index.php?search=highway&title=Special%3ASearch&profile=advanced&fulltext=1&ns120=1) in the Item: namespace returns an internal server error. Normally it would return results for items that contain the text “highway” in some fashion.

**Comment by tomhughes** [comment]
I see the red error box but I can't actually seem to get a full trace...

**Comment by 1ec5** [comment]
It logs directly to the browser console:

```
RuntimeException: the current site has to be of type MediaWikiSite
Backtrace:
from /srv/test.wiki.openstreetmap.org/w/extensions/Wikibase/lib/includes/Modules/CurrentSiteModule.php(99)
#0 /srv/test.wiki.openstreetmap.org/w/extensions/Wikibase/lib/includes/Modules/CurrentSiteModule.php(78): Wikibase\Lib\Modules\CurrentSiteModule->makeScript()
#1 /srv/test.wiki.openstreetmap.org/w/includes/libs/objectcache/BagOStuff.php(217): Wikibase\Lib\Modules\CurrentSiteModule->Wikibase\Lib\Modules\{closure}()
#2 /srv/test.wiki.openstreetmap.org/w/extensions/Wikibase/lib/includes/Modules/CurrentSiteModule.php(74): Wikimedia\ObjectCache\BagOStuff->getWithSetCallback()
#3 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(843): Wikibase\Lib\Modules\CurrentSiteModule->getScript()
#4 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(812): MediaWiki\ResourceLoader\Module->buildContent()
#5 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(955): MediaWiki\ResourceLoader\Module->getModuleContent()
#6 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/StartUpModule.php(222): MediaWiki\ResourceLoader\Module->getVersionHash()
#7 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/StartUpModule.php(431): MediaWiki\ResourceLoader\StartUpModule->getModuleRegistrations()
#8 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(843): MediaWiki\ResourceLoader\StartUpModule->getScript()
#9 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(812): MediaWiki\ResourceLoader\Module->buildContent()
#10 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(955): MediaWiki\ResourceLoader\Module->getModuleContent()
#11 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/ResourceLoader.php(686): MediaWiki\ResourceLoader\Module->getVersionHash()
#12 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/ResourceLoader.php(786): MediaWiki\ResourceLoader\ResourceLoader->getCombinedVersion()
#13 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/ResourceLoaderEntryPoint.php(54): MediaWiki\ResourceLoader\ResourceLoader->respond()
#14 /srv/test.wiki.openstreetmap.org/w/includes/MediaWikiEntryPoint.php(200): MediaWiki\ResourceLoader\ResourceLoaderEntryPoint->execute()
#15 /srv/test.wiki.openstreetmap.org/w/load.php(42): MediaWiki\MediaWikiEntryPoint->run()
#16 {main}
```

https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/b6b7ca310798cac058b2fb25038355d876df7736/lib/includes/Modules/CurrentSiteModule.php#L99

Looks like we’ve subclassed `Site` rather than [`MediaWikiSite`](https://github.com/wikimedia/mediawiki/blob/40fdb9a16e6a0175159220bd3d3cd0fb2c38403e/includes/site/MediaWikiSite.php#L35):

https://github.com/nyurik/OsmWikibase/blob/234833cacef684d67034966bbe0bf31e4a294e9c/includes/OsmSite.php#L38

nyurik/OsmWikibase#4

**Comment by 1ec5** [comment]
I’m getting the same error on the test site when autocompleting a property name or statement value in a data item. For example, the error appears when loading [this data item](https://test.wiki.openstreetmap.org/wiki/Item:Q21162). Then if you click “add statement” and type “status”, nothing shows up. This makes it impossible to edit a data item other than to delete statements. I don’t see this issue on the production site.

**Comment by tomhughes** [comment]
Why is this only showing up now and only on the test server though?

**Comment by tomhughes** [comment]
I've hacked the inheritance on the test server, which just changes the exception...

```
RuntimeException: getFileUrl called for wiki while PATH_FILE is unset
Backtrace:
from /srv/test.wiki.openstreetmap.org/w/includes/site/MediaWikiSite.php(203)
#0 /srv/test.wiki.openstreetmap.org/w/extensions/Wikibase/lib/includes/Modules/SitesModuleBase.php(106): MediaWiki\Site\MediaWikiSite->getFileUrl()
#1 /srv/test.wiki.openstreetmap.org/w/extensions/Wikibase/lib/includes/Modules/CurrentSiteModule.php(102): Wikibase\Lib\Modules\SitesModuleBase->computeSiteDetails()
#2 /srv/test.wiki.openstreetmap.org/w/extensions/Wikibase/lib/includes/Modules/CurrentSiteModule.php(78): Wikibase\Lib\Modules\CurrentSiteModule->makeScript()
#3 /srv/test.wiki.openstreetmap.org/w/includes/libs/objectcache/BagOStuff.php(217): Wikibase\Lib\Modules\CurrentSiteModule->Wikibase\Lib\Modules\{closure}()
#4 /srv/test.wiki.openstreetmap.org/w/extensions/Wikibase/lib/includes/Modules/CurrentSiteModule.php(74): Wikimedia\ObjectCache\BagOStuff->getWithSetCallback()
#5 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(843): Wikibase\Lib\Modules\CurrentSiteModule->getScript()
#6 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(812): MediaWiki\ResourceLoader\Module->buildContent()
#7 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(955): MediaWiki\ResourceLoader\Module->getModuleContent()
#8 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/StartUpModule.php(222): MediaWiki\ResourceLoader\Module->getVersionHash()
#9 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/StartUpModule.php(431): MediaWiki\ResourceLoader\StartUpModule->getModuleRegistrations()
#10 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(843): MediaWiki\ResourceLoader\StartUpModule->getScript()
#11 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(812): MediaWiki\ResourceLoader\Module->buildContent()
#12 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/Module.php(955): MediaWiki\ResourceLoader\Module->getModuleContent()
#13 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/ResourceLoader.php(686): MediaWiki\ResourceLoader\Module->getVersionHash()
#14 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/ResourceLoader.php(786): MediaWiki\ResourceLoader\ResourceLoader->getCombinedVersion()
#15 /srv/test.wiki.openstreetmap.org/w/includes/ResourceLoader/ResourceLoaderEntryPoint.php(54): MediaWiki\ResourceLoader\ResourceLoader->respond()
#16 /srv/test.wiki.openstreetmap.org/w/includes/MediaWikiEntryPoint.php(200): MediaWiki\ResourceLoader\ResourceLoaderEntryPoint->execute()
#17 /srv/test.wiki.openstreetmap.org/w/load.php(42): MediaWiki\MediaWikiEntryPoint->run()
#18 {main}
```

**Comment by 1ec5** [comment]
It’s probably not enough to just extend `MediaWikiSite`; there’s a bunch of things to implement too. But everything about the `OsmSite` class looks like a hack (and even says so). Maybe @nyurik could opine on whether we need to properly implement the class or whether it’s a red herring for something else?

**Comment by 1ec5** [comment]
The documentation for OsmWikibase [says to set `Site::PATH_LINK`](https://github.com/nyurik/OsmWikibase/blob/234833cacef684d67034966bbe0bf31e4a294e9c/README.md?plain=1#L23), but the main MediaWiki documentation [says to set `MediaWikiSite::PATH_PAGE` and `MediaWikiSite::PATH_FILE`](https://www.mediawiki.org/wiki/Manual:Sites_table#Insert_wiki_family_(using_Script)).

**Comment by 1ec5** [comment]
I’m still getting the errors in https://github.com/openstreetmap/operations/issues/903#issuecomment-2849289301 and https://github.com/openstreetmap/operations/issues/903#issuecomment-2852072003 after the fix for nyurik/OsmWikibase#4.

**Comment by 1ec5** [comment]
As of the upgrade to MediaWiki 1.46, the error looks a bit different:

> An error has occurred while searching: We could not complete your search due to a temporary problem. Please try again later.

Nothing gets logged to the browser console anymore.

**Comment by 1ec5** [comment]
@Firefishy set `PATH_FILE` per https://github.com/openstreetmap/operations/issues/903#issuecomment-2852632484. This solved the errors momentarily, but I’m getting it again. Not sure if things got reverted by accident.

Going back to https://github.com/openstreetmap/operations/issues/903#issuecomment-2848577387, [`haswbstatement:P6=Q15`](https://test.wiki.openstreetmap.org/w/index.php?search=haswbstatement%3AP6%3DQ15&title=Special%3ASearch&profile=advanced&fulltext=1&ns120=1) still doesn’t return any results, even if I [pass in `useCirrus=1`](https://test.wiki.openstreetmap.org/w/index.php?search=haswbstatement%3AP6%3DQ15&title=Special%3ASearch&profile=advanced&fulltext=1&ns120=1&useCirrus=1). (That shouldn’t be necessary anyways, because we already [set `$wgWBCSUseCirrus`](https://github.com/openstreetmap/chef/blob/552a9a59fc638385e53cbf1b9e72ce7ecfca6f84/cookbooks/wiki/templates/default/mw-ext-WikibaseCirrusSearch.inc.php.erb#L6).)
