### ISSUE TITLE
Replying to Emails not working

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/operations#991]
### How to reproduce the issue?

I got this error when replying to an email:

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [m-1146468-a9jZs9m1@messages.openstreetmap.org](mailto:m-1146468-a9jZs9m1@messages.openstreetmap.org)
    local delivery failed

The following text was generated during the delivery attempt:

------ [m-1146468-a9jZs9m1@messages.openstreetmap.org](mailto:m-1146468-a9jZs9m1@messages.openstreetmap.org) ------

WARN: advpng none at /bin/advpng (== none) is of unknown version
/var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/application.rb:641:in `validate_secret_key_base': Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit` (ArgumentError)
        from /var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/application.rb:479:in `secret_key_base'
        from /var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/application.rb:199:in `block in message_verifiers'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/message_verifiers.rb:132:in `build'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/messages/rotation_coordinator.rb:85:in `block in build_with_rotations'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/messages/rotation_coordinator.rb:85:in `map'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/messages/rotation_coordinator.rb:85:in `build_with_rotations'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/messages/rotation_coordinator.rb:19:in `[]'
        from /var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/application.rb:223:in `message_verifier'
        from /var/lib/gems/3.0.0/gems/activerecord-7.1.1/lib/active_record/railtie.rb:374:in `block (3 levels) in <class:Railtie>'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:62:in `block in on_load'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:61:in `each'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:61:in `on_load'
        from /var/lib/gems/3.0.0/gems/activerecord-7.1.1/lib/active_record/railtie.rb:373:in `block (2 levels) in <class:Railtie>'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:94:in `block in execute_hook'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:77:in `each'
        from /var/lib/gems/3.0.0/gems/activesupport-7.1.1/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
        from /var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/application/finisher.rb:93:in `block in <module:Finisher>'
        from /var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `run'
        from /var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/initializable.rb:60:in `run_initializers'
        from /var/lib/gems/3.0.0/gems/railties-7.1.1/lib/rails/application.rb:423:in `initialize!'
        from /srv/[www.openstreetmap.org/rails/config/environment.rb:5:in](http://www.openstreetmap.org/rails/config/environment.rb:5:in) `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /srv/[www.openstreetmap.org/rails/script/deliver-message:3:in](http://www.openstreetmap.org/rails/script/deliver-message:3:in) `<main>'
```

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/9224925dad40dabb3cc09cdaf0c5c30ee3bfc818.
